---
title: "Mapping aphid and parasitoid samples"
date: ""
editor_options:
  chunk_output_type: inline
output:
  pdf_document:
    toc: yes
  html_document:
    theme: yeti
    toc: yes
    toc_float: yes
author: Youn
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, message = FALSE, warning = FALSE)
```


# Packages

```{r load-packages}
# [R v4.2.1]
library(tidyverse) # CRAN v1.3.1
library(ggmap) # CRAN v3.0.0
library(osmdata) # CRAN v0.1.10
library(ggtext) # CRAN v0.1.1
library(ggrepel) # CRAN v0.9.1
library(patchwork) # CRAN v1.1.1
library(here) # CRAN v1.0.1
## tool for workspace location management
## automatically detects the workspace after loading the package if Rstudio was opened using the script file (or with new R project)
## load last to avoid conflicts
```

# Overview

We start by loading the data

```{r load-data}
data_aphids <- read.table(
  here("data", "aphid_samples_2020.txt"),
  h = T, dec = "."
) %>%
  mutate(sample_id = str_replace(sample_id, "Y20-", "TR-")) %>%
  mutate(aphid_species = str_replace_all(aphid_species, "_", " ")) %>%
  mutate(aphid_species = paste("*", aphid_species, "*", sep = "")) %>%
  mutate(sample_id_to_draw = case_when(
    transfected == "yes" ~ sample_id,
    TRUE ~ ""
  ))

head(data_aphids)

data_parasitoids <- read.table(
  here("data", "parasitoid_samples_2020.txt"),
  h = T, dec = "."
) %>%
  mutate(aphid_species = str_replace_all(aphid_species, "_", " ")) %>%
  mutate(aphid_species = paste("*", aphid_species, "*", sep = ""))

head(data_parasitoids)
```

# Mapping

Then we do some general preparation: defining a bounding, box, the colours for the legend, loading the map background:

```{r prepare-maps}
bounding_box <- c(
  left = 8.145,
  bottom = 47.295,
  right = 8.77,
  top = 47.575
)

colors0 <- c(
  "*Aphis urticata*" = "#ff9900", # same colors as in analysis code, but too "flashy" on maps. Adjust?
  "*Aphis ruborum*" = "#88ff4d",
  "*Aphis fabae fabae*" = "#66ccff",
  "*Aphis hederae*" = "#aa80ff"
)

colors <- c(
  "*Aphis urticata*" = "#e68a00",
  "*Aphis ruborum*" = "#53c71a",
  "*Aphis fabae fabae*" = "#00a0f0",
  "*Aphis hederae*" = "#5c0aff"
)

mymap <- get_stamenmap(
  bbox = bounding_box,
  maptype = "terrain", zoom = 11
)
```

Now we can build the map. First the aphid/*Hamiltonella* map:

```{r map-aphids}
mapPointsA <- ggmap(mymap, darken = c(0.2, "white")) +
  geom_point(
    data = data_aphids,
    aes(x = longitude, y = latitude, colour = aphid_species),
    size = 3, alpha = 0.6
  ) +
  geom_label_repel(
    data = data_aphids,
    aes(
      x = longitude, y = latitude,
      label = sample_id_to_draw, colour = aphid_species
    ),
    segment.colour = "black",
    size = 3, max.overlaps = Inf, nudge_x = 0.02, nudge_y = 0.005,
    box.padding = 0.2,
    min.segment.length = 0, xlim = c(bounding_box["left"], NA)
  ) +
  labs(x = "longitude", y = "latitude") +
  scale_color_manual(
    name = "Host species",
    values = colors
  ) +
  geom_richtext(
    data = data.frame(),
    aes(label = "*Hamiltonella defensa*", x = Inf, y = Inf),
    hjust = 1, vjust = 1, label.size = NA, label.r = unit(0, "lines")
  ) +
  guides(colour = "none") +
  theme(
    legend.text = element_markdown(),
    axis.text.x = element_blank(),
    axis.title.x = element_blank()
  )

mapPointsA

pdf(height = 4, width = 5, file = here("R_output", "Aphid_map.pdf"))
mapPointsA
dev.off()
```

Then the parasitoid map:

```{r map-parasitoids}
mapPointsP <- ggmap(mymap, darken = c(0.2, "white")) +
  geom_point(
    data = data_parasitoids,
    aes(
      x = longitude, y = latitude,
      colour = aphid_species,
      shape = niche
    ),
    size = 3, alpha = 0.8
  ) +
  geom_label_repel(
    data = subset(
      data_parasitoids,
      data_parasitoids$niche == "generalist"
    ),
    aes(x = longitude, y = latitude, label = genotype),
    size = 3, max.overlaps = Inf, nudge_x = 0.02, nudge_y = 0.005,
    box.padding = 0.2, force_pull = 5,
    min.segment.length = 0, xlim = c(bounding_box["left"], NA)
  ) +
  labs(x = "longitude", y = "latitude") +
  scale_color_manual(
    name = "Host species",
    values = colors
  ) +
  scale_shape_discrete("Range of hosts (parasitoids)") +
  geom_richtext(
    data = data.frame(),
    aes(label = "*Lysiphlebus fabarum*", x = Inf, y = Inf),
    hjust = 1, vjust = 1, label.size = NA, label.r = unit(0, "lines")
  ) +
  guides(colour = guide_legend(order = 1), 
         shape = guide_legend(order = 2)) +
  theme(
    legend.text = element_markdown()
  )

mapPointsP

pdf(height = 4, width = 5, file = here("R_output", "Parasitoid_map.pdf"))
mapPointsP
dev.off()
```

Finally the combined map for publication, using the `patchwork` package:

```{r combined-maps}

# version with stacked panels

pdf(height = 7, width = 7, file = here("R_output", "stacked_maps.pdf"))

(mapPointsA / mapPointsP) +
  plot_layout(guides = "collect")

dev.off()
```
